collections:
  activities:
    output: true

#host: 192.168.0.199

#theme: jekyll-theme-hacker
title: "Karmanyaah Malhotra"
description: "This is my personal website for experimentation and having a profile that I maintain on the WWW."
google_analytics: "UA-103015933-2"


defaults:
  - scope:
      path: ""
      type: "activities"
    values:
      layout: "activity"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag


#    github default
 #   jekyll-coffeescript
  #  jekyll-default-layout
   # jekyll-gist
#    jekyll-github-metadata
 #   jekyll-optional-front-matter
  #  jekyll-paginate
   # jekyll-readme-index
#    jekyll-titles-from-headings
 #   jekyll-relative-links


lsi: false
safe: true
#source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge


## Settings
owner: "Karmanyaah Malhotra"
url: "http://www.karmanyaah.me"
baseurl: ""
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "karmanyaahm@gmail.com"
github: "karmanyaahm/karmanyaahm.github.io"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "All Rights Reserved?"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 6
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
