collections:
  activities:
    output: true

host: 192.168.0.199

#theme: jekyll-theme-hacker
title: "Karmanyaah Malhotra"
description: "This is my personal website for experimentation and having a profile that I maintain on the WWW."
google_analytics: "UA-103015933-2"


defaults:
  - scope:
      path: ""
      type: "activities"
    values:
      layout: "activity"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag


#    github default
 #   jekyll-coffeescript
  #  jekyll-default-layout
   # jekyll-gist
#    jekyll-github-metadata
 #   jekyll-optional-front-matter
  #  jekyll-paginate
   # jekyll-readme-index
#    jekyll-titles-from-headings
 #   jekyll-relative-links


lsi: false
safe: true
#source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

destination: ../_site
keep_files: [".git",".gitignore"]
## Settings
owner: "Karmanyaah Malhotra"
url: ""
baseurl: ""
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "karmanyaahm@gmail.com"
github: "karmanyaahm/karmanyaahm.github.io"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "All Rights Reserved?"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 6
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"


############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
webp:
  enabled: true
  
  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/img"]

  # Whether to search in nested directories or not
  nested: false

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files 
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
############################################################