#host: 192.168.0.199
livereload: true

theme: jekyll-theme-hydeout
title: "Karmanyaah Malhotra"
description: "My personal website bc y not"
analytics: kar
author:
  name:           'Karmanyaah Malhotra'
  url:            https://karmanyaah.malhotra.cc/about
  gemuri: gemini://karmanyaah.malhotra.cc/
permalink: /:categories/:year/:month/:title/
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      showposts: true
  - scope:
      path: ""
      type: "gemlog"
    values:
      layout: "gemlog"
      sitemap: false
  - scope:
      path: ""
      type: "go"
    values:
      layout: "go"
      sitemap: false
  - scope:
      path: "gemini"
    values:
      sitemap: false
collections:
  gemlog:
    output: true
    permalink: /gemini/gemlog/:path:output_ext
  go:
    output: true
    permalink: /k.malhotra.cc/go/:path/

url: "https://karmanyaah.malhotra.cc" #for sitemap
domain: karmanyaah.malhotra.cc

paginate:         15
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-purgecss
#    github default
#   jekyll-coffeescript
#  jekyll-default-layout
# jekyll-gist
#    jekyll-github-metadata
#   jekyll-optional-front-matter
#  jekyll-paginate
# jekyll-readme-index
#    jekyll-titles-from-headings
#   jekyll-relative-links

    #lsi: false
    #safe: true
    ##source: [your repo's top level directory]
    #highlighter: rouge
    #gist:
    #  noscript: false
    #kramdown:
    #  math_engine: mathjax
    #  syntax_highlighter: rouge
    #
    #destination: _site
    #keep_files: [".git", ".gitignore"]
    #include: [".well-known"]
    ### Settings
    #owner: "Karmanyaah Malhotra"
    #
    #baseurl: ""
    #webrick:
    #  headers:
    #    Access-Control-Allow-Origin: "*"
    ### Global Variables
    #email: ""
    #aboutmeenable: false
    #github: "karmanyaahm/karmanyaahm.github.io"
    ## path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets"
css_dir: assets/css
    #statement: "All Rights Reserved?"
    ## default max toc levels: 1 - 6 (h1 - h6)
    #toc_level: 6
    ###########Possible bugs
    ##list of articles.html > using site.url
    #
sass:
  sass_dir: assets/_sass
  style: compressed
    #
    #compress_html:
    #    clippings: []
    #    comments: []
    #    endings: []
    #    ignore:
    #      envs: []
    #    blanklines: false
    #    profile: false
    #    startings: []
    #    #testing
    #
    #


