collections:
  activities:
    output: true

defaults:
  - scope:
      path: ""
      type: "activities"
    values:
      layout: "activity"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"