collections:
  activities:
    output: true

host: 192.168.0.199

#theme: jekyll-theme-hacker
title: "Karmanyaah Malhotra"
description: "This is my personal website for experimentation and having a profile that I maintain on the WWW."
google_analytics: false

defaults:
  - scope:
      path: ""
      type: "activities"
    values:
      layout: "activity"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

url: "https://www.karmanyaah.me" #for sitemap
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier

#    github default
#   jekyll-coffeescript
#  jekyll-default-layout
# jekyll-gist
#    jekyll-github-metadata
#   jekyll-optional-front-matter
#  jekyll-paginate
# jekyll-readme-index
#    jekyll-titles-from-headings
#   jekyll-relative-links

lsi: false
safe: true
#source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

destination: ../_site
keep_files: [".git", ".gitignore"]
## Settings
owner: "Karmanyaah Malhotra"

baseurl: "/"
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: ""
aboutmeenable: false
github: "karmanyaahm/karmanyaahm.github.io"
# path to: css/, fonts/, img/ and js/
assets_path: "assets" # i.e. "/assets"
statement: "All Rights Reserved?"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 6
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
##########Possible bugs
#list of articles.html > using site.url

sass:
  sass_dir: assets/_sass
  style: compressed

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
  #testing
